vich_uploader:
    db_driver: orm

    mappings:
        user_image:
            uri_prefix: /profile
            upload_destination: '%kernel.project_dir%/public/profile'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
